### ISSUE TITLE
README Update

### ISSUE THREAD

**Issue by CKKK** [ccanow/mongoose-audit-log#1]
Hi, 
Thank you very much for the package. Is there anyway that you can update the documentation for this package. I am trying to use it but keeps telling me User missing in audit log. And there is no documentation for me to fix this problem.

**Comment by ccanow** [comment]
Hi,
thanks for your interest, will update the documentation asap.

I think an audit log should always know "who" did something, so I decided to have the user being mandatory...
What you basically want to do is either specify the user on the document before persist (i.e. myModel.__user = { any: 'kind of object/data you want' }) or override the "global" handler to get the current logged in user (my preference). In order to do so, you can override the "getUser" method like below (require('./passport').userContext contains the current user (e.g. {id:xyz, name:abc}); normally you only need the users ID).

`
const auditLog = require('mongoose-audit-log').plugin;
const userContext = require('./passport').userContext;

module.exports = () => {
  auditLog.getUser = () => userContext.user.id;
};
`

Hope that'll help!

**Comment by ccanow** [comment]
See README.md for more information
